# Generated by Django 3.1.4 on 2021-03-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('nationality', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FairyTale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('times_read', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.author')),
            ],
        ),
    ]
