# Generated by Django 3.2 on 2021-05-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairytale',
            name='image',
            field=models.FilePathField(default=1, path='/img'),
            preserve_default=False,
        ),
    ]
