# Generated by Django 3.2 on 2021-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_fairytale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fairytale',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
