# Generated by Django 3.2 on 2021-05-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210508_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fairytale',
            name='image',
        ),
    ]
