# Generated by Django 3.2 on 2021-06-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_fairytale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairytale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
