# Generated by Django 3.2 on 2021-06-11 18:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_fairytale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairytale',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
