# Generated by Django 3.2 on 2021-06-12 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210612_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Subject',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='subject_choose',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='theme',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
