# Generated by Django 3.2 on 2021-06-12 08:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210612_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
