# Generated by Django 3.2 on 2021-06-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_comment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
