# Generated by Django 3.2 on 2021-06-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsSection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='person_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='subject_choose',
            new_name='subject',
        ),
    ]
