# Generated by Django 3.2 on 2021-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsSection', '0005_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
